logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8888
  ssl:
    key-store: keystore.p12
    key-store-password: 111111
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  session:
    store-type: redis
  application:
    name: gateway-service
  jpa:
    open-in-view: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://demo.anyun100.com:3306/anyun_storage?useUnicode=true&characterEncoding=utf-8
    username: xd_guan
    password: Angang1109                                          
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitive-headers:
      serviceId: OATH2-SERVER
    client:
      path: /api/v1/admin/client/**
      url: http://192.168.68.48:8000/api/v1/admin/client
    admin:
      path: /api/v1/admin/**
      serviceId: ADMIN
      sensitive-headers:
    region-center-1:
      path: /api/v1/region-center/1/**
      serviceId: REGION-CENTER-1
      sensitive-headers:
    region-center-2:
      path: /api/v1/region-center/2/**
      serviceId: REGION-CENTER-2
      sensitive-headers:
    region-center-3:
      path: /api/v1/region/**
      serviceId: REGION-CENTER-3
      sensitive-headers:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 600000
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000  

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
        timeout:
          enabled: false
security:
  oauth2:
    resource:
      filter-order: 3
